### ISSUE TITLE
problem for installation 1.2.4

### ISSUE THREAD

**Issue by cnzxcxt1** [yukai-yang/PSTR#5]
hello,
I just come across a problem when installing the package of version 1.2.4.
* installing *source* package 'PSTR' ...
** R
Error : (由警告转换成)无法重新编码'PSTR.R'行41
ERROR: unable to collate and parse R files for package 'PSTR'
* removing 'D:/R/R-3.5.3/library/PSTR'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/Xiangtuo/AppData/Local/Temp/RtmpyaO9AV/file3d10d956938/PSTR_1.2.4.tar.gz’ had non-zero exit status

could you help me to have a look?

best regards

**Comment by yukai-yang** [comment]
May I ask how you installed the package? By using

install.packages("PSTR")

?

**Comment by cnzxcxt1** [comment]
then it is not the newest version.
--------------------------------
陈 相托
Simon Chen
Tel：+86 13401170598
Email: cnzxcxt1@sina.com

----- 原始邮件 -----
发件人：凱(Kai) <notifications@github.com>
收件人：yukai-yang/PSTR <PSTR@noreply.github.com>
抄送人：cnzxcxt1 <cnzxcxt1@sina.com>,  Author <author@noreply.github.com>
主题：Re: [yukai-yang/PSTR] problem for installation 1.2.4 (#5)
日期：2019年04月30日 14点24分

May I ask how you installed the package? By using
install.packages("PSTR")
?

**Comment by yukai-yang** [comment]
OK, I see. You are trying to install the newest version from Github by using

`devtools::install_github("yukai-yang/PSTR")`

It seems from the message you've shown that there is some problem in the PSTR.R file, line 41. You can find it in the source code.

`#' González, A., Teräsvirta, T., van Dijk, D. and Yang, Y. (2005) "\href{http://swopec.hhs.se/hastef/papers/hastef0604.pdf}{Panel Smooth Transition Regression Models}", SSE/EFI Working Paper Series in Economics and Finance 604, Stockholm School of Economics, revised 11 Oct 2017.`

Probably this is due to that your local R environment does not recognize the special characters like á, ä ...

Hope this helps...
